README.md, package.json
added npm live-server
@LuuLuu0
=> Package settings

src/components/related-items/RelatedItems.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx
Renamed main related items file and implemented basic skeleton structure for related items module.
@gilcohen67
=> Renamed main related items file and implemented basic skeleton

src/components/App.jsx, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/related-items/RelatedItems.jsx, src/context/GlobalStore.jsx
Refactored the Global Context
@gilcohen67
=> Context testing

src/components/product-detail/add_to_cart/addToCart.jsx, src/components/product-detail/image_gallery/imageGallery.jsx, src/components/product-detail/productDetail.jsx, src/components/product-detail/product_information/productInfo.jsx, src/components/product-detail/style_selector/styleSelector.jsx, src/components/related-items/RelatedItems.jsx
updated skeleton with global store
@LuuLuu0
=> updated skeleton for prod detail and global store

package-lock.json, package.json, server/controllers/index.js, server/controllers/reviews.js, server/routes.js, src/components/ratings-reviews/reviews/reviews-list/ReviewsList.jsx
@eghkuang 
Added routes npm install needed for path and express.
=> Server routes

.eslintrc.json, config.sample.js, server/controllers/reviews.js, server/routes.js, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/OverallRating.jsx, src/components/ratings-reviews/ratings/Ratings.jsx, src/components/ratings-reviews/ratings/SpecBars.jsx, src/components/ratings-reviews/ratings/StarBars.jsx, src/components/ratings-reviews/reviews/MoreAndAdd.jsx, src/components/ratings-reviews/reviews/OverviewAndSort.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewTile.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewsList.jsx
=> Fixed fetch errors and added linter rule

server/controllers/index.js, server/controllers/related.js, server/controllers/reviews.js, server/routes.js, src/components/related-items/RelatedItems.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx, src/context/GlobalStore.jsx
changed to use global context, 
WIP on related items client and server.
=> WIP Related Items List

server/controllers/related.js, src/components/App.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx, src/context/GlobalStore.jsx
=> Implemented related list map to related cards

.eslintrc.json, server/controllers/reviews.js, server/routes.js, src/components/ratings-reviews/ratings/OverallRating.jsx
get request from /reviews/meta/:id to get average rating.
=> server touchup. meta now returns average and total ratings

server/controllers/reviews.js, server/routes.js, src/components/App.jsx, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/OverallRating.jsx, src/components/ratings-reviews/reviews/MoreAndAdd.jsx, src/components/ratings-reviews/reviews/OverviewAndSort.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewsList.jsx
=> Show more fix

.eslintrc.json, package-lock.json, package.json, server/controllers/reviews.js, src/components/App.jsx, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/OverallRating.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewTile.jsx, src/context/GlobalStore.jsx, src/context/RAndRContext.jsx, src/styles.css
=> Review tile

package-lock.json, package.json, src/components/App.jsx, src/components/related-items/carousel/Carousel.css, src/components/related-items/carousel/Carousel.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedItems.css, src/components/related-items/related/relatedList.jsx
=> CSS implementation for Related Items, still need to work Carousel

src/components/App.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/related/compareModal.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx, src/context/GlobalStore.jsx, src/styles.css, tests/RelatedItems.test.jsx
Ready for review @gilcohen67 @eghkuang
=> Implemented the comparison modal for related items

.eslintrc.json, src/components/App.jsx, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/OverallRating.jsx, src/components/ratings-reviews/ratings/ProductBreakdown.jsx, src/components/ratings-reviews/ratings/RatingBreakdown.jsx, src/components/ratings-reviews/ratings/Ratings.jsx, src/components/ratings-reviews/ratings/SpecBars.jsx, src/components/ratings-reviews/reviews/MoreAndAdd.jsx, src/components/ratings-reviews/reviews/OverviewAndSort.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewTile.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewsList.jsx, src/components/ratings-reviews/write-review/WriteReview.jsx, src/components/related-items/outfit/outfitCard.jsx, src/context/GlobalStore.jsx, src/context/RAndRContext.jsx, src/styled-lib/index.js, src/styles.css, tests/RatingsAndReviews.test.jsx
changed some App things to fit my context in a bit better, and added css.
=> Ratings breakdown

src/components/App.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/compareModal.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx
Up for review @eghkuang @gilcohen67
=> Implemented working Modal and outfit section. Still need work on CSS

src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/relatedCard.jsx, src/styles.css
=> Fixed carousel and changed empty outfit card

src/components/related-items/related/relatedCard.jsx, tests/RelatedItems.test.jsx
One functional test for related items.
Ready for Review
@gilcohen67 @eghkuang
=> Test suite for Related Items

server/controllers/reviews.js, server/routes.js, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/OverallRating.jsx, src/components/ratings-reviews/ratings/ProductBreakdown.jsx, src/components/ratings-reviews/ratings/RatingBreakdown.jsx, src/components/ratings-reviews/ratings/Ratings.jsx, src/components/ratings-reviews/reviews/MoreAndAdd.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewTile.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewsList.jsx, src/components/ratings-reviews/write-review/WriteReview.jsx, src/context/GlobalStore.jsx, src/context/RAndRContext.jsx, src/styled-lib/index.js, src/styles.css
All helpful and report functionality done. Helpful and report data saved in local storage. Also changed whole app to be flex box to center our widgets [Open to changes to that].
=> Helpful report

src/components/related-items/RelatedItems.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/compareModal.jsx, src/components/related-items/related/relatedCard.jsx, src/components/related-items/related/relatedList.jsx, src/styles.css
=> CSS Changes to widget

src/components/App.jsx, src/components/NavBar.jsx, src/components/ratings-reviews/RatingsAndReviews.jsx, src/context/RAndRContext.jsx, src/styles.css
=> State cleanup rr

src/components/product-detail/add_to_cart/addToCart.jsx, src/components/product-detail/add_to_cart/quantities.jsx, src/components/product-detail/image_gallery/imageGallery.jsx, src/components/product-detail/productDetail.jsx, src/components/product-detail/product_information/productInfo.jsx, src/components/product-detail/style_selector/styleSelector.jsx
added productId and productInfo to useEffect in imageGallery
=> fixed render issues

src/components/related-items/RelatedItems.jsx, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/related/relatedCard.jsx
=> Outfit Button

package-lock.json, package.json, server/controllers/reviews.js, src/components/ratings-reviews/RatingsAndReviews.jsx, src/components/ratings-reviews/ratings/ProductBreakdown.jsx, src/components/ratings-reviews/reviews/reviews-list/ReviewTile.jsx, src/components/ratings-reviews/write-review/WriteReview.jsx, src/context/RAndRContext.jsx, src/styles.css
=> Updated some package.json scripts and dependencies

dist/index.html, src/components/product-detail/add_to_cart/addToCart.jsx, src/styles.css
added some fonts that all look the similar ha
=> font time woohoooo

package-lock.json, package.json, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/outfit/outfitList.jsx, src/components/related-items/related/relatedCard.jsx
=> CSS Changes to related items cards, outfit cards, and buttons

server/controllers/related.js, src/components/related-items/outfit/outfitCard.jsx, src/components/related-items/related/relatedCard.jsx, src/context/GlobalStore.jsx
=> LAST MINUTE ADDITIONS AND CHANGES
